clear;

summTable = readtable('scoreTable.csv');

numImg = height(summTable);

fid = fopen('image_data.js', 'w');
fprintf(fid, 'var rating_data = [];\n');

for ii = 1:numImg
    fprintf(fid, ['rating_data.push({ ', ...
        '"name": "', num2str(ii, '%05d'), '.jpg", ', ...
        '"walkability": ', num2str(summTable.Walkability(ii)), ', ', ...
        '"preference": ', num2str(summTable.Preference(ii)), ', ', ...
        '"imageability": ', num2str(summTable.Imageability(ii)), ', ', ...
        '"complexity": ', num2str(summTable.Complexity(ii)), ', ', ...
        '"enclosure": ', num2str(summTable.Enclosure(ii)), ', ', ...
        '"humanscale": ', num2str(summTable.Humanscale(ii)), ', ', ...
        '"transparency": ', num2str(summTable.Transparency(ii)), ', ', ...
        '"disorder": ', num2str(summTable.Disorder(ii)), ' });\n']);
end

fclose(fid);


